name: Release Please (release-please.yml)

env:
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"
  VCPKG_NUGET_REPOSITORY: https://github.com/hpcc-systems/hpcc-js-wasm

on:
  push:
    branches:
      - main
    tags:
      - "**"

permissions:
  contents: write
  pull-requests: write
  packages: write
  pages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Release Please
        if: github.ref == 'refs/heads/main'
        id: release
        uses: googleapis/release-please-action@v5.0.0
        with:
          target-branch: ${{ github.ref_name }}
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Checkout Sources
        uses: actions/checkout@v7.0.0

      - name: Install NodeJS
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
          scope: "@hpcc-js"

      - name: Install OS Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo apt-get install -y git cmake ninja-build wget zip
          sudo apt-get install -y gcc-multilib g++-multilib pkg-config autoconf libtool
          sudo apt-get install -y python3 python3-pip
          sudo apt-get install -y mono-complete

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v9.0.0
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install Dependencies
        run: |
          npm ci
          npm run install-build-deps

      - name: Make nuget.exe executable
        run: |
          NUGET_PATH=$(./vcpkg/vcpkg fetch nuget | tail -n 1)
          chmod +x "$NUGET_PATH"

      - name: Setup vcpkg NuGet authentication
        run: |
          mono `./vcpkg/vcpkg fetch nuget | tail -n 1` \
            sources add \
            -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            -storepasswordincleartext \
            -name "GitHub" \
            -username "${{ github.actor }}" \
            -password "${{ secrets.GITHUB_TOKEN }}"
          mono `./vcpkg/vcpkg fetch nuget | tail -n 1` \
            setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Lint
        if: github.ref == 'refs/heads/main'
        run: |
          npm run lint

      - name: Build
        run: |
          npm run build

      - name: Test
        if: github.ref == 'refs/heads/main'
        run: |
          npm run test

      - name: Build Docs
        if: github.ref == 'refs/heads/main'
        run: |
          test -f packages/graphviz/dist/index.js
          npm run build-docs

      - name: Deploy Docs
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.vitepress/dist
          force_orphan: true
        env:
          CI: true

      - name: Calculate Coverage
        if: github.ref == 'refs/heads/main'
        continue-on-error: true
        run: |
          npm run coverage

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm run publish

      - name: Purge jsdelivr
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          npm run purge-jsdelivr
